### ISSUE TITLE
Resolve the issues caused by vibration and lighting at AU: source materials

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Herbarium-Sheets-workstation#121]
With Digitizer Charlotte Hansen in full swing in Aarhus the issues of vibration from the table and insufficient lighting have become untenable. 

- [x] [Research, gather specs and pricing & communicate options to solve their issues](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/121#issuecomment-2331291854)

- [x] [Get confirmation that table will work](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/121#issuecomment-2331299428)

- [x] [Order the table](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/121#issuecomment-2331310058)

- [x] [Get confirmation on whether light stands will work](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/121#issuecomment-2331315674)

- [x] [Get confirmation on whether scaffolding will work](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/121#issuecomment-2331325901)

- [ ] Order scaffolding supplies

- [x] Create ticket for building a new scaffolding and installing scaffolding and lamps at Herbarium AAU

**Comment by chelseagraham** [comment]
### Research and communicate options to solve their problems

- [x] find measurements and pricing for the 240 kg load bearing table that we have ordered at Herbarium C so that Birgitte can gauge whether it would be feasible at Herbarium AAU (this table exceeds the size of the elevator at Herbarium AAU)

**Load Bearing Table at Herbarium C’s imaging Workstations**
https://www.nielsbo.dk/collections/lager-og-transportudstyr_arbejdsborde-pakkebe-haevesaenkeborde_haevesaenkeborde/products/2000-mm-bog-massiv-27-mm-mobilt-haeve-saenkebord

_Size_
2000 x 800 x 1090 mm
Astrid measured the following (plus images attached):
Underside of image table: 149 cm
Length of feet: 78 cm

_Capacity_
240 kg

_Price_
**13.325,00 kr** excluding moms

- [x] find measurements for table fitting the elevator at AAU

_Current Table at AAU_
2000 cm x 770 cm

- [x] find specs for lamps (already purchased and currently located in ZM room 249)

**Lights: Nanlux TK-200**
https://goecker.dk/nanlux-tk-200-daylight-soft-panel

_Size_
89 cm x 54 cm x 8.5 cm

_Weight_
5,68 kg

_Fixture mounting_
1x 1-1/8" Stud with 5/8" Receiver (Via Yoke Mount)

- [x] find specs and pricing for scaffolding material for an enclosure

**Scaffolding at Herbarium C’s imaging Workstations**

_Size_
1380 mm x 700 mm x 1605 mm

_Estimated Price_ 
**6.260,44 DKK**

- [x] find specs and pricing for an alternative light stand option

**Possible Light Stands: Manfrotto 1004BAC Master Stand**
https://www.lightpartner.dk/manfrotto-1004bac-master-stand.html

_Capacity_
Up to 9 kg
Min height 124 cm, Max height 366 cm

_Fixture mounting_
Top attachment: adapter art. 015, type 19, Male Attachment: 16, Male Attachment 2: 3/8" / 1/4"

_Price_
692,80 kr each excluding moms x 2 = **1385,60 kr total**

- [x] communicate with Pip and Birgitte

emails: 
28 August
3 September

[Re: AAU table and light supports.pdf](https://github.com/user-attachments/files/16892072/Re.AAU.table.and.light.supports.pdf)

**Comment by chelseagraham** [comment]
### Get confirmation that table will work

Birgitte confirmed that we should order the load bearing table during our Aarhus & NHMD weekly meeting on Monday, 2 September

email:

[Aarhus & NHMD Meeting recap .pdf](https://github.com/user-attachments/files/16892741/Aarhus.NHMD.Meeting.recap.pdf)

**Comment by chelseagraham** [comment]
### Order the table

Table ordered from Niels Bo

email:
[FW: Ordren #7276 er bekræftet.pdf](https://github.com/user-attachments/files/16892843/FW.Ordren.7276.er.bekraeftet.pdf)

Order confirmation:
[Salg Ordre 93274.pdf](https://github.com/user-attachments/files/16892830/Salg.Ordre.93274.pdf)

19 September
Inquired about an estimated date of delivery
Niels Bo answered: Afsendelses dato: 26/9/2024 (by end of week 39)

7 October
Charlotte emailed to confirm that they received the table.

**Comment by chelseagraham** [comment]
### Get confirmation that scaffolding will work

Checked with Birgitte about size of scaffolding on 3 September

_Size_
1380 mm x 700 mm x 1605 mm

email:
[Re: AAU table and light supports.pdf](https://github.com/user-attachments/files/16892877/Re.AAU.table.and.light.supports.pdf)

**Comment by chelseagraham** [comment]
### Get confirmation on whether scaffolding will work

Checked with Birgitte about size of scaffolding on 3 September
Followed up on 10, 11, 16, 18 September

_Size_
1380 mm x 700 mm x 1605 mm

email:
[Re: AAU table and light supports.pdf](https://github.com/user-attachments/files/16892877/Re.AAU.table.and.light.supports.pdf)

In an email dated 24 September, Birgitte confirmed that measurements work.
email:
[Enclosure.pdf](https://github.com/user-attachments/files/17259182/Enclosure.pdf)

**Comment by chelseagraham** [comment]
@Gomismis tells me there is a plan for transporting the enclosure from WORKHERB0003 to Herbarium AAU for use at WORKHERB0002 with @RebekkaML :)

Great!

Please create a GitHub ticket for that and link it in this ticket. 
Please remember to include time for deconstructing the enclosure out at Priorparken and getting the materials (including the enclosure, toolbox, safety wires for the lamps, clamps for the lamps and lamps that are in room 249 at ZM) organized for transport (1 day)

@RebekkaML and @nms419 are you in touch about ordering the replacement materials for the scaffolding?

**Comment by nms419** [comment]
Info about scaffolding material can be found in issue #61 and info about the clamps can be found in issue #62. Let me know if you have any questions otherwiser @RebekkaML.
